version: '3'
services:
  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      # Add additional devices as needed

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto
    restart: unless-stopped
    privileged: true
    # If Mosquitto needs access to specific devices, add them here

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  nodered_data:
  influxdb_data:
  mosquitto_data:
  grafana_data:
